Schema: Remove mixed types: road.flags (Parquet compatibility)
OvertureMaps/schema pull request #135
Opened 2024-02-27 22:34 UTC by TheRBajaj

# Description

This PR removes the mixed schema types for `road.flags` property

### Before
`road.flags` could accept multiple types of values that could be put into the same property like array and string values.

### After

`roads.flags` only accepts array property instead of array and string

# Reference

https://github.com/OvertureMaps/tf-transportation/issues/57

# Testing

Tested using test script

2024-02-28 00:00 UTC, marinrelatic submitted a review, later dismissed

2024-02-28 16:16 UTC, brad-richardson submitted a review, later dismissed

2024-02-28 16:18 UTC, bastiaanvanassche-tomtom approved these changes

2024-02-28 19:44 UTC, sanjibdutta1 approved these changes

2024-02-29 16:18 UTC, vcschapp requested changes
@TheRBajaj need to fix counterexamples.

1. [ ] There are many existing `counterexamples` that have the old-style flags, but where the intention of those counterexamples isn't to find an error in the `road.flags` property. Can you please find and fix them all to use new-style flags?
2. [x] Please get in the habit of looking for counterexamples to fix when doing schema changes!
3. [ ] Could you also add one counterexample that explicitly tests for invalid old-style flags?

2024-02-29 16:25 UTC, vcschapp commented
@TheRBajaj are you using the pull request template?

Looking at this PR's description, it looks like the template was deleted or trimmed-down. If you're doing that, it's preferable not to.

These are the benefits of the PR template:

1. It has a standard format, so it makes it easier to find expected information in expected places.
2. It helps you not forget things.
3. It has a checklist. Explicitly on the checklist, there's an entry for "Add relevant counterexamples", which would help you remember to do that in this case.

2024-03-01 17:43 UTC, vcschapp approved these changes
```
                   __
                  / \--..____
                   \ \       \-----,,,..
                    \ \       \         \--,,..
                     \ \       \         \  ,'
                      \ \       \         \ ``..
                       \ \       \         \-''
                        \ \       \__,,--'''
                         \ \       \.
                          \ \      ,/
                           \ \__..-
                            \ \
                             \ \
                              \ \   :F_P:
                               \ \
                                \ \
                                 \ \
                                  \ \
                                   \ \
                                    \ \
```

2024-03-01 18:17 UTC, brad-richardson requested changes

2024-03-01 18:17 UTC, brad-richardson commented on counterexamples/transportation/segment/road/restrictions/turns/bad-turns-reason.yaml
> +      - [is_link, is_tunnel, isPrivate]
Shouldn't these be `is_private`?

2024-03-01 20:40 UTC, brad-richardson submitted a review, later dismissed
It looks like you have some conflicts to resolve first but LGTM!

2024-03-01 22:00 UTC, sanjibdutta1 approved these changes

2024-03-01 22:15 UTC, ibnt1 approved these changes

2024-03-01 23:13 UTC, vcschapp commented
> It looks like you have some conflicts to resolve first but LGTM!

I see it also. @TheRBajaj could you resolve the conflict to make this PR mergable?

2024-03-04 19:24 UTC, vcschapp commented
Merging this despite the fact that validation is currently broken. Some cross-PR conflicts caused merging several previous PRs that by themselves were fine to break validation. It will be easier to merge this first, then fix after.

2024-03-04 19:25 UTC, merged