Restructure and remove mixed schema types for speed_limits property
OvertureMaps/schema pull request #141
Opened 2024-03-07 22:12 UTC by TheRBajaj

# Description

This PR remodels the `road.restrictions.speed_limits` type to only allow `value` and `unit` properties. The `unit` property uses current speed unit enumeration as the enumerated value domain. This also ensures that `road.restrictions.speed_limits` does not handle mixed schema types

# Reference

https://github.com/OvertureMaps/tf-transportation/issues/99

# Testing

Tested using test script

# Checklist

*Checklist of tasks commonly-associated with schema pull requests. Please review the relevant checklists and ensure you do all the tasks that are required for the change you made.*

1. [ ] Add relevant examples.
2. [ ] Add relevant counterexamples.
3. [ ] Update in-schema documentation using plain English written in complete sentences, if an update is required.
4. [ ] Update Docusaurus documentation, if an update is required.
5. [ ] Review change with Overture technical writer to ensure any advanced documentation needs will be taken care of, unless the change is trivial and would not affect the documentation.

# Documentation Website

*Update the hyperlink below to put the pull request number in.*

[Docs preview for this PR.](https://dfhx9f55j8eg5.cloudfront.net/pr/<PUT THE PR # HERE>)

2024-03-07 22:19 UTC, ibnt1 submitted a review, later dismissed

2024-03-07 22:23 UTC, brad-richardson approved these changes

2024-03-08 00:06 UTC, marinrelatic commented on schema/transportation/segment.yaml
> +          description: Number of speed units
nit: These descriptions sound somewhat ridiculous. How about
```
value:
  description: speed value
...
unit:
  description: speed unit
```

2024-03-08 00:07 UTC, marinrelatic submitted a review, later dismissed

2024-03-08 00:07 UTC, marinrelatic commented
Small nit comment. Otherwise, looks good to me

2024-03-11 16:45 UTC, vcschapp requested changes
One small change, everything else looks great.

2024-03-11 16:45 UTC, vcschapp commented on schema/transportation/segment.yaml
>        additionalItems: false
This should switch to `unevaluatedProperties: false`. The `additionalItems` property only applies to arrays, not objects.

2024-03-12 00:57 UTC, brad-richardson approved these changes

2024-03-12 14:56 UTC, bastiaanvanassche-tomtom approved these changes

2024-03-12 16:15 UTC, vcschapp approved these changes

2024-03-12 17:07 UTC, sanjibdutta1 approved these changes

2024-03-12 23:04 UTC, merged