Add genus/species to land
OvertureMaps/schema pull request #194
Opened 2024-05-21 20:12 UTC by jenningsanderson

# Description

Adds more OSM tags — species, genus to the `source_tags` for the `land` type which includes trees. 

TODO.

# Reference

Requested by Esri

1. TODO.

# Testing

*Brief description of the testing done for this change showing why you are confident it works as expected and does not introduce regressions. Provide sample output data where appropriate.* 

TODO.

# Checklist

*Checklist of tasks commonly-associated with schema pull requests. Please review the relevant checklists and ensure you do all the tasks that are required for the change you made.*

1. [ ] Add relevant examples.
2. [ ] Add relevant counterexamples.
3. [ ] Update any counterexamples that became obsolete. For example, if a counterexample uses property `A` but is not intended to test property `A`'s validity, and you made a schema change that invalidates property `A` in that counterexample, fix the counterexample to align it with your schema change.  
4. [ ] Update in-schema documentation using plain English written in complete sentences, if an update is required.
5. [ ] Update Docusaurus documentation, if an update is required.
6. [ ] Review change with Overture technical writer to ensure any advanced documentation needs will be taken care of, unless the change is trivial and would not affect the documentation.

# Documentation Website

*Update the hyperlink below to put the pull request number in.*

[Docs preview for this PR.](https://dfhx9f55j8eg5.cloudfront.net/pr/<PUT THE PR # HERE>)

2024-05-21 21:20 UTC, BoZivk approved these changes

2024-05-21 22:48 UTC, jwass submitted a review, later dismissed

2024-05-22 00:42 UTC, skmoore requested changes
Can we also add height, est_height, min_height, diameter_crown, leaf_type, leaf_cycle, taxon, taxon:species, taxon:cultivar, and denotation. We currently use all of these tags to create our 3d trees layer from Daylight.

2024-05-22 15:34 UTC, jwass approved these changes

2024-05-22 15:35 UTC, DavidKarlas approved these changes

2024-05-22 15:35 UTC, TristanDiet-TomTom approved these changes

2024-05-22 15:35 UTC, vcschapp approved these changes

2024-05-22 16:27 UTC, skmoore approved these changes

2024-05-22 16:27 UTC, merged