Buildings roof height: eave_height -> roof_height
OvertureMaps/schema pull request #201
Opened 2024-05-28 13:00 UTC by jwass

Replace eave_height with roof_height. Overture release data has not populated eave_height up to now so this shouldn't have downstream effects for users other than the column name change.

Use roof height instead of eave_height. The buildings task force decided that roof height was more standard and easier to reason about than providing the eave_height value. 

1. [x ] Add relevant examples.
2. [ ] Add relevant counterexamples.
3. [ ] Update any counterexamples that became obsolete. For example, if a counterexample uses property `A` but is not intended to test property `A`'s validity, and you made a schema change that invalidates property `A` in that counterexample, fix the counterexample to align it with your schema change.  
4. [x ] Update in-schema documentation using plain English written in complete sentences, if an update is required.
5. [ ] Update Docusaurus documentation, if an update is required.
6. [ ] Review change with Overture technical writer to ensure any advanced documentation needs will be taken care of, unless the change is trivial and would not affect the documentation.

# Documentation Website

*Update the hyperlink below to put the pull request number in.*

[Docs preview for this PR.](https://dfhx9f55j8eg5.cloudfront.net/pr/<PUT THE PR # HERE>)

2024-05-28 16:38 UTC, skmoore requested changes

2024-05-28 16:38 UTC, skmoore commented on schema/buildings/defs.yaml
I would maybe say '...to the highest point of the roof' instead of '...to the top of the roof'.

2024-05-28 19:28 UTC, jenningsanderson submitted a review, later dismissed
Is roof line synonymous with "eave" ? If so, maybe include that term?

2024-05-28 19:33 UTC, skmoore commented
> Is roof line synonymous with "eave" ? If so, maybe include that term?

I considered that as well, just not sure how familiar people are with that term. Also, many buildings (like my house and many other houses in Southern Arizona) don't have eaves.

2024-05-28 20:30 UTC, jwass commented on schema/buildings/defs.yaml
Thanks! I made this change.

2024-05-28 20:35 UTC, skmoore approved these changes

2024-05-28 20:46 UTC, jwass commented
@skmoore @jenningsanderson I clearly wasn't sure how to phrase that but changed to "This represents the distance from the base of the roof to the highest point of the roof." 

I'm happy to take any suggestions

2024-05-29 08:03 UTC, LukaszMichalski-TomTom approved these changes

2024-05-29 15:03 UTC, vcschapp approved these changes

2024-05-29 15:03 UTC, jenningsanderson approved these changes

2024-05-29 15:53 UTC, DavidKarlas approved these changes

2024-05-29 15:58 UTC, merged