Adding support for disputed administrative boundaries
OvertureMaps/schema pull request #53
Opened 2023-09-26 13:22 UTC by DavidKarlas

This is adding new optional property to administrative boundaries that indicates to rendering how to handle disputed boarder.

2023-09-26 13:35 UTC, jonahadkins approved these changes
LGTM 🗺️

2023-09-26 14:27 UTC, jwass commented
I'm not sure I understand the purpose of 'hidden' and why it's needed. Is it injecting too much opinion in the dataset?

2023-09-26 14:51 UTC, DavidKarlas commented
I had same question why do we need hidden, and why don't we just drop(not include) such boundary in dataset. Answer was and I agree with logic, to allow verification that all boundaries form polygon around administrative locality/entity. There should only be handful of cases where we use this feature.

2023-09-26 20:23 UTC, varapmsft approved these changes

2023-09-27 03:09 UTC, jwass commented
> I had same question why do we need hidden, and why don't we just drop(not include) such boundary in dataset. Answer was and I agree with logic, to allow verification that all boundaries form polygon around administrative locality/entity. There should only be handful of cases where we use this feature.

Sorry but I don't understand. If this is to capture disputed linestrings, what are the boundaries being provided?

2023-09-27 10:01 UTC, TristanDiet-TomTom commented
> Sorry but I don't understand. If this is to capture disputed linestrings, what are the boundaries being provided that are hidden?

The hidden value would not be applied to disputed linestring, rather would it be applied to administrative country borders in data.

There is a difference between showing a defined border which is disputed and not showing a border because no common border has been defined. In the latter, showing any border could trigger discussions in 'hypersensitive' areas. An example is the Line of Control (LoC) between India and Pakistan which formally ends in NJ9842. Showing any country border north of this point even as disputed could be sensitive to either party. 

>I'm not sure I understand the purpose of 'hidden' and why it's needed. Is it injecting too much opinion in the dataset?
In light of the above, it is therefore not injecting too much opinion in the dataset, rather less.

2023-09-27 10:05 UTC, TristanDiet-TomTom approved these changes
No further disputes from my side ;)

2023-10-02 15:20 UTC, dkensok approved these changes

2023-10-04 15:26 UTC, merged

2023-10-04 16:02 UTC, vcschapp requested changes
I think we merged this already, but a couple of (late) feedback points.

2023-10-04 16:07 UTC, vcschapp commented
> There is a difference between showing a defined border which is disputed and not showing a border because no common border has been defined. In the latter, showing any border could trigger discussions in 'hypersensitive' areas. An example is the Line of Control (LoC) between India and Pakistan which formally ends in NJ9842. Showing any country border north of this point even as disputed could be sensitive to either party.

But that's not how geopolitical perspectives work is it?

Presumably there's a line that India thinks is the border and a line Pakistan thinks is the border. If you're rendering a map from India's perspective, you want it to look the way India sees it, and if you're viewing it from Pakistan's perspective you want it to look the way Pakistan sees it. So it's not about whether it's "hidden" or not, it's about whose perspective your adopting. If there's a third perspective which is the "we don't have an opinion and don't want to offend anyone from any country so we're leaving it out" perspective, then that's a third perspective on it. But that doesn't mean the line is "hidden", it means that from a certain perspective the line does not exist.

2023-10-04 16:10 UTC, vcschapp commented on schema/admins/administrativeBoundary.yaml
> +        enum: [disputed, hidden, visible]
(Regarding tagging the polygons, see the *Feature-Oriented Civics Schema* proposal on Confluence.)

2023-10-04 16:16 UTC, DavidKarlas commented
Notice that this PR is not about different perspectives but for "default" international view and rendering of disputed borders.
Example with disputed border:
<img width="438" alt="image" src="https://github.com/OvertureMaps/schema/assets/774791/9316dff6-78b9-4bac-819b-b64bcb408260">
Example with hidden border:
![image](https://github.com/OvertureMaps/schema/assets/774791/d57ad45d-8a84-4fdf-a770-a4b31b6dc45c)
Example where maritime is forced to be rendered:
![image](https://github.com/OvertureMaps/schema/assets/774791/f4fdbefc-baaa-48cc-8b57-0a69b68218f5)

2023-10-04 16:19 UTC, DavidKarlas commented on schema/admins/administrativeBoundary.yaml
> +      geopolDisplay:
I found property name a bit weird, but since nobody objected it I left it as is...
We can still change if you want.

2023-10-04 16:21 UTC, DavidKarlas commented on schema/admins/administrativeBoundary.yaml
> +        description: Optional value that indicates if the boundary needs special rendering logic
Again, this PR is not about political perspectives, it is about how border should be rendered when there is dispute. If both countries agree to disagree but we still want to render some border(as people live for example) we can render it dashed...

2023-10-04 18:24 UTC, vcschapp commented
Sticking just with the bottom example ("*Example where maritime is forced to be rendered*"), it seems like the underlying state that we want to capture is that it's a border between two countries.

Some might choose to render that line on their map tiles, others might not, so I don't think `geopolDisplay: visible` is capturing the underlying data - because we're capturing the data in terms of a subjective cartographic decision.

**NB**: In the [Feature-Oriented Civics Schema](https://wiki.overturemaps.org/x/nwEjAQ) doc, this would be a feature of type `border` (core semantics) on which anyone could make a cartographic decision to render it, or not, as they chose.

2023-10-05 15:53 UTC, jwass commented
> Sticking just with the bottom example ("_Example where maritime is forced to be rendered_"), it seems like the underlying state that we want to capture is that it's a border between two countries.
> 
> Some might choose to render that line on their map tiles, others might not, so I don't think `geopolDisplay: visible` is capturing the underlying data - because we're capturing the data in terms of a subjective cartographic decision.
> 
> **NB**: In the [Feature-Oriented Civics Schema](https://wiki.overturemaps.org/x/nwEjAQ) doc, this would be a feature of type `border` (core semantics) on which anyone could make a cartographic decision to render it, or not, as they chose.

I had brought this up in the admins group as well and my understanding is that "hidden" was a near universal agreement among map providers that this border line is always hidden. But otherwise I have similar concerns as you as to whether Overture is injecting too strong of an opinion here.

2023-10-06 00:38 UTC, vcschapp commented
I think we are. It's encrusting a point-in-time cartographic decision as a permanent schema attribute.

The thing is, we can communicate the same underlying data to Overture consumers so they can make the same cartographic conclusion if they want to, without jumping to that conclusion.

It's just a matter of framing it in a more general way, as what it's status is (disputed) and by whom, instead of what to do about it (hide it).

To bring it back to the second example ("Example with hidden border"), a map that is literally provided by an Overture member (Esri) shows that whole area as part of India with a solid border *if you toggle it to the India political perspective*. So this model won't work for Esri.

2023-10-06 01:09 UTC, varapmsft commented
_To bring it back to the second example ("Example with hidden border"), a map that is literally provided by an Overture member (Esri) shows that whole area as part of India with a solid border if you toggle it to the India political perspective. So this model won't work for Esri._

Not really, it is still possible to meet Esri needs. One way to do it is to have a border for the India view with no geopolDisplay property and another border for ROW view with 'hidden' value. There are other ways to model without duplicating the feature as well, which can be discussed when we model 'multiple perspectives'.

Please note that just this property alone will not meet many of the needs of Esri or any other Overture member.