fix: spelling of cafeteria
OvertureMaps/schema pull request #86
Opened 2023-11-30 18:00 UTC by JanCallewaert-TomTom

2023-12-05 06:31 UTC, klayton-symbiosis requested changes
You didn't change the second spelling (in the tree path)

2023-12-05 19:07 UTC, klayton-symbiosis approved these changes

2023-12-07 18:32 UTC, JanCallewaert-TomTom commented
> The commit history doesn't make sense to me - there are 23 commits to merge in the PR, but the description is perfunctory and suggests a change which should only require one very minimal commit ("fix: spelling of cafeteria").
> 
> Assuming the `dev` branch is the correct branch to target, I think you should ensure your local repo's commit history is closer to `dev` before creating the PR...

I have rebased on `dev`. Should be fine now.

2023-12-13 16:12 UTC, vcschapp approved these changes

2023-12-13 16:13 UTC, merged

2023-12-13 16:13 UTC, DavidKarlas approved these changes

2023-12-13 16:13 UTC, Dritte commented
Looks good to me