Added roof shape and material mapping files
OvertureMaps/schema pull request #89
Opened 2023-12-05 16:26 UTC by LukaszMichalski-TomTom

Added mapping files for OSM values to Overture enumeration values.
Additional values:
**facadeMaterial**:
- clay
- timber_framing

**roofMaterial**
- gravel
- solar_panels

**roofShape**:
- saltbox
- skillion
- sawtooth

Four roof shape names changed to OSM equivalents, e.g. `gable`→`gabled`. I did it to make it more in line with OSM tooling and possible renders that can generate roof geometry based on this value. If someone would like to use Overture data to generate visualization, it may be easier for them.

2023-12-06 21:49 UTC, jwass reviewed
@LukaszMichalski-TomTom I realize these aren't all your doing, but can you make all the Overture values camelCased?

It's the standard (even though I don't love it).

2023-12-07 03:12 UTC, jwass commented
@LukaszMichalski-TomTom Just so I understand... facadeMaterial describes the mapping for 
* `building:material=*`  (and also `building:facade:material`?)
* roofMaterial is for `roof:material`
* roofShape is for `roof:shape`
??

2023-12-07 21:20 UTC, skmoore requested changes

2023-12-12 14:40 UTC, LukaszMichalski-TomTom commented
> @LukaszMichalski-TomTom Just so I understand... facadeMaterial describes the mapping for
> 
> * `building:material=*`  (and also `building:facade:material`?)
> * roofMaterial is for `roof:material`
> * roofShape is for `roof:shape`
>   ??

I will add README next to mapping files to describe osm tag that need to be used. 
`overture_facadeMaterial_OSM_mapping.json` file contains mapping of OSM values to Overture `facedMaterial` property. OSM tags used for mapping in order:
- `building:material` (documentation: https://wiki.openstreetmap.org/wiki/Key:building:material)
- `building:facade:material` (documentation: https://wiki.openstreetmap.org/wiki/Key:building:facade:material)

`overture_roofMaterial_OSM_mapping.json` file contains mapping of OSM values to Overture `roofMaterial` property. OSM tags used for mapping:
- `roof:material` (documentation: https://wiki.openstreetmap.org/wiki/Key:roof:material)

`overture_roofShape_OSM_mapping.json` file contains mapping of OSM values to Overture `roofShape` property. OSM tags used for mapping in order:
- `roof:shape` (documentation: https://wiki.openstreetmap.org/wiki/Key:roof:shape)
- `building:roof:shape` (deprecated, documentation: https://wiki.openstreetmap.org/wiki/Key

2023-12-12 14:43 UTC, LukaszMichalski-TomTom commented on task-force-docs/buildings/overture_roofMaterial_OSM_mapping.json
> +    "zink",
I will add `zinc` with 3 692 occurrences, but I will leave `zink` witch has 3 261.

2023-12-12 16:34 UTC, ArthurTCrawford commented on task-force-docs/buildings/overture_roofMaterial_OSM_mapping.json
> +    "zink",
The German spelling is zink for zinc.

2024-01-31 17:31 UTC, vcschapp commented
Reminder: @jwass took the action to consult with the PR authors and determine if this can be brought back to life.

2024-02-14 04:13 UTC, jwass submitted a review, later dismissed

2024-02-14 16:05 UTC, skmoore approved these changes

2024-02-14 16:20 UTC, vcschapp approved these changes

2024-02-14 16:24 UTC, TristanDiet-TomTom submitted a review, later dismissed

2024-02-14 16:24 UTC, DavidKarlas approved these changes

2024-02-21 01:04 UTC, vcschapp commented on task-force-docs/buildings/overture_roofShape_OSM_mapping.json
> +    "gabred",
garbled?

2024-02-21 01:05 UTC, vcschapp commented on task-force-docs/buildings/overture_facadeMaterial_OSM_mapping.json
> +}
@LukaszMichalski-TomTom could you fix your tooling setup so it adds a newline at the end of the files?

2024-02-21 01:06 UTC, vcschapp requested changes
Could you please:

1. [x] Fix `facedMaterial` to `facadeMaterial`? (typo in the `README.md`)
2. [x] Ensure the files end in a newline (should not have the no newline at EOF icon at the bottom of every diff)

2024-02-21 01:06 UTC, vcschapp commented on task-force-docs/buildings/README.md
> +`overture_facadeMaterial_OSM_mapping.json` file contains mapping of OSM values to Overture `facedMaterial` property. OSM tags used for mapping in order:
`facedMaterial` looks like a typo, should be `facadeMaterial` no?

2024-02-23 00:08 UTC, jenningsanderson commented
@LukaszMichalski-TomTom I updated these to be `snake_case` in-line with the new schema updates and added them all to one file.

These are out-of-sync with the current logic in the buildings airflow pipeline and schema, which is causing hundreds of thousands of errors.

Can you confirm that these are the correct mappings, and then I will update the logic here: https://github.com/OvertureMaps/tf-data-platform/blob/dev/datapipelines/airflow/dags/overture/query_fragments.py#L118 to reflect what's here.

2024-02-23 20:37 UTC, jenningsanderson commented
Based on the current logic in the mapping JSON file (https://github.com/OvertureMaps/schema/pull/89/files#diff-5e18ae5feffd2d58657bf46be190bc986fb510fc7ee3b69f0e2d185828f4fad1), here are the counts for thee entire building theme: 

|roof_shape |_count|
|-------|---------|
| gabled | 4159376 |
| flat | 1370802 |
| hipped | 756957 |
| pyramidal | 249441 |
| skillion | 188343 |
| half_hipped | 100036 |
| saltbox | 55879 |
| round | 39348 |
| gambrel | 32996 |
| mansard | 23322 |
| dome | 16401 |
| onion | 5980 |
| sawtooth | 600 |
| spherical | 26 |


|roof_material | count|
|-------|---------|
| roof_tiles | 856423 |
| metal | 187222 |
| eternit | 129954 |
| concrete | 127903 |
| slate | 58635 |
| glass | 38825 |
| thatch | 21904 |
| grass | 12637 |
| plastic | 7316 |
| copper | 7299 |
| gravel | 7153 |
| wood | 3715 |
| solar_panels | 179 |


|facade_material | count|
|-------|---------|
| brick | 514852 |
| cement_block | 448061 |
| plaster | 398151 |
| wood | 210496 |
| concrete | 174449 |
| metal | 91201 |
| stone | 41789 |
| glass | 38035 |
| clay | 30661 |
| plastic | 16514 |
| timber_framing | 9975 |

2024-02-26 16:41 UTC, jenningsanderson commented
I added `tar_paper` as an acceptable value because it's the 4th largest on OSM

2024-02-28 00:58 UTC, vcschapp approved these changes
```
    ) )        /\
   =====      /  \
  _|___|_____/ __ \____________
 |::::::::::/ |  | \:::::::::::|
 |:::::::::/  ====  \::::::::::|
 |::::::::/__________\:::::::::|
 |_________|  ____  |__________|
  | ______ | / || \ | _______ |
  ||  |   || ====== ||   |   ||
  ||--+---|| |    | ||---+---||
  ||__|___|| |   o| ||___|___||
  |========| |____| |=========|
 (^^-^^^^^-|________|-^^^--^^^)
 (,, , ,, ,/________\,,,, ,, ,)
','',,,,' /__________\,,,',',;;
```

2024-02-28 16:19 UTC, DavidKarlas approved these changes

2024-02-28 18:37 UTC, merged